export default {
    // #
    '404': 'Content not found.',
    '400': 'Client error.',
    '401': 'Unauthorized',
    '500': 'Something went wrong.',
    // region A
    address: 'Địa chỉ',
    address2: '153 Đồng Khởi, Phường Bến Nghé, Quận 1 - Thành phố Hồ Chí Minh',
    bankName2: 'Ngân hàng',
    branch: 'Chi nhánh',
    aboutUs: 'About us',
    apply: 'Apply',
    amount: 'Amount',
    amount2: 'Số lượng',
    amountOfMoney: 'Số tiền',
    amountPayment: 'Tiền thanh toán',
    amountPayment2: 'Số tiền cần thanh toán',
    allAmountPayment: 'Tổng số tiền cần thanh toán',
    acc: 'Tài khoản',
    accountHolder: 'Chủ tài khoản',
    individual: 'Cá nhân',
    account: 'Tài khoản',
    accountBenefits: 'TÀI KHOẢN HƯỞNG THỤ',
    accountBenefits2: 'TÀI KHOẢN THỤ HƯỞNG',
    accept: 'Accept',
    asset: 'Tài sản',
    area: 'Khu vực',
    accountVerification: 'Xác minh tài khoản',
    assetAndIncomeVerification: 'Xác thực tài sản và thu nhập',
    addAsset: 'Thêm tài sản',
    assetInformation: 'Thông tin thu nhập',
    advise: 'Tư vấn',
    accountVerification2: 'Xác thực tài khoản',
    accountGolfer: 'Tài khoản Golfer',
    addressContact: 'Địa chỉ liên hệ',
    authenticationChannel: 'Kênh xác thực',
    authenticGolfer: 'Xác thực Golfer',
    assetVerification: 'Xác thực tài sản',
    addPicture: 'Thêm ảnh',
    assetGroup: 'Nhóm tài sản',
    assetName: 'Tên tài sản',
    addAssetInformation: 'Thêm thông tin thu nhập',

    accountName: 'Tên tài khoản:',
    accountNumber: 'Số tài khoản:',
    accountNumber2: 'Số tài khoản',
    accountNameValue: 'Nguyễn Thị A',
    accountNumberValue: '12312412312512312',
    addNew: 'Thêm mới',
    addNewAccount: 'Thêm mới tài khoản',
    accordingToTheDecreasingBalancePlaceholder: 'Theo dư nợ giảm dần',
    applyForALoan: 'Đăng ký vay',
    all: 'TẤT CẢ',
    allBorrowing: 'Tổng vay',
    paid: 'Đã trả',
    debt: 'Dư nợ',
    amountBorrowing: 'Số tiền vay',
    authenticationStatus: 'Trạng thái xác thực',
    additionalInformation: 'Thông tin bổ sung',
    andMustNotExceed: 'và không được vượt quá',
    amountPaid: 'Số kỳ đã thanh toán',
    amountRequestedForReduction: 'Số tiền yêu cầu giảm',
    addBeneficiaryAccount: 'Thêm tài khoản thụ hưởng',
    amountToBeDisbursed: 'Số tiền cần giải ngân',
    amountCanDisbursed: 'Số tiền có thể giải ngân',
    attractiveAndCompetitiveInterest:
        'Lãi suất hấp dẫn và cạnh tranh \n Thủ tục đơn giản và giải ngân nhanh chóng \n Pháp lý rõ ràng',
    approvedLimit: 'Hạn mức đã phê duyệt',
    approving: 'Đang phê duyệt',
    approved: 'Đã phê duyệt',
    approved2: 'Đã duyệt',
    AddBeneficiaryInformation: 'Thêm thông tin thụ hưởng',
    addToSuccessfulAccount: 'thêm mới tài khoản thành công',
    accountUpdateSuccessful: 'Cập nhật tài khoản thành công',
    accountDeletedSuccessful: 'Xóa tài khoản thành công',
    ageMustBeOver18: 'Tuổi phải trên 18',
    // endregion

    // region B
    body: 'Body',
    borrowing: 'ĐANG VAY',
    borrower: 'Bên vay',
    borrowing2: 'Đang vay',
    borrowingStatus: 'HIỆN TRẠNG VAY',
    bookMark: 'Bookmark',
    birthdate: 'Birthdate',
    brand: 'Thương hiệu',
    businessInformation: 'Thông tin doanh nghiệp',
    beneficiaryAccount: 'Tài khoản thụ hưởng',
    informationBeneficiaryAccount: 'Thông tin tài khoản hưởng thụ',
    bookGolf: 'Đặt sân golf',
    bankName: 'Ngân hàng Thương mại cổ phần Việt Nam Thịnh Vượng (VPBank)',
    beneficiaryInformation: 'Thông tin người thụ hưởng',
    borrowingContract: 'Quản lý hợp đồng vay',
    manageLoanAmount: 'Quản lý hồ sơ khoản vay',
    manageAmount: 'Quản lý khoản vay',
    managementMobilizationRecords: 'Quản lý hồ sơ huy động',
    backToHome: 'Về trang chủ',
    browsingProfile: 'Đang duyệt hồ sơ',
    billingInformation: 'Thông tin thanh toán',
    biometricNotSp: 'Thiết bị không hỗ trợ đăng nhập bằng FaceID/TouchID',
    // endregion

    // region C
    changePassword: 'Đổi mật khẩu',
    closed: 'ĐÃ ĐÓNG',
    changeThePassword: 'Thay đổi mật khẩu',
    cancel: 'Huỷ',
    completed: 'Completed',
    confirm: 'Xác nhận',
    continue: 'Tiếp theo',
    complete: 'Complete',
    comingSoon: 'Coming soon',
    contract: 'Hợp đồng',
    contractOnline: 'HỢP ĐỒNG ONLINE',
    contractOffline: 'HỢP ĐỒNG OFFLINE',
    checkSmsToReceiveOtp:
        'Vui lòng kiểm tra tin nhắn SMS của bạn để nhận mã OTP.',
    createNewPassword: 'Tạo mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    createNewPasswordSuccess: 'Tạo mật khẩu mới thành công',
    companyName: 'Tên công ty',
    career: 'Ngành nghề',
    content: 'Nội dung',
    cooperatingWithLeading:
        'Hợp tác với các đơn vị bảo hiểm hàng đầu Việt Nam, mang lại những giải pháp bảo vệ vượt trội',
    contactTheSwitchboard:
        'Quý khách muốn thay đổi thông tin cá nhân và xác thực vui lòng liên hệ với T99 qua số tổng đài',
    changeAvatar: 'Thay đổi ảnh đại diện',
    change: 'Thay đổi',
    cmnd: 'CMND/CCCD',
    clientAuthenticationStatus: 'Trạng thái xác thực khách hàng',
    paymentStatus: 'TRẠNG THÁI THANH TOÁN',
    paymentSuccess: 'Đã thanh toán',
    clientInformation: 'Thông tin khách hàng',
    cmndCccdRegistered: 'Số CCCD/CMND/Hộ chiếu bạn đã đăng ký',
    cmndCccdRegisteredLabel: 'Số CCCD/CMND/Hộ chiếu đã đăng ký',
    cooperatingWithLeadingInsurance:
        'Hợp tác với các đơn vị bảo hiểm hàng đầu Việt Nam, mang lại những giải pháp bảo vệ vượt trội',
    centerSupport: 'Trung tâm trợ giúp',
    confirmTheValidationResult: 'Xác nhận kết quả xác thực',
    confirmationOfResidence: 'Xác thực nơi cư trú',

    chooseTypeToCalculateInterest: 'Chọn loại cần tính lãi',
    chooseProductCalculateProfitTypeEstimate:
        'Vui lòng lựa chọn sản phẩm bạn muốn tính lãi dự kiến',
    calculatingLoanInterest: 'Tính lãi vay',
    calculatingDepositInterest: 'Tính lãi huy động',
    calculation: 'Cách tính',
    contractInfo: 'THÔNG TIN HỢP ĐỒNG',
    contractPayments: 'Thanh toán hợp đồng',
    citizenIDWithChip: 'Căn cước công dân gắn chip',
    cardType: 'Loại giấy tờ',
    contactsAddress: 'Địa chỉ liên hệ',
    contactsAddressLabel: 'Địa chỉ liên hệ giống địa chỉ thường trú',
    contactsAddressLabel2: 'Số nhà,  tên đường, quận/huyện, tỉnh thành phố',
    chooseTheTypeOfContractPaymentForOthers:
        'Chọn loại thanh toán hợp đồng cho người khác',
    choosePaymentMethod: 'Chọn hình thức thanh toán',
    contractCode: 'Mã hợp đồng',
    contractSettlement: 'Tất toán hợp đồng',
    copyTheFollowingContent: 'copy nội dung sau',
    contractSettlementInformation: 'Thông tin tất toán hợp đồng',
    collateral: 'Tài sản thế chấp',
    chooseTradeRoom: 'Chọn phòng giao dịch',
    cmtcccdpassport: 'CMT/CCCD/Hộ chiếu',
    convert: 'Đổi',
    cmndcccdNumber: 'Số CMND/CCCD',
    confirmInformation: 'Xác nhận thông tin',
    cashConsumptionLoan: 'Vay tiêu dùng tiền mặt',
    chooseDate: 'Chọn ngày',
    coverImage: 'Ảnh bìa',
    creditLimit: 'Hạn mức tín dụng',
    createAccountSuccess: 'Tạo tài khoản thành công',
    createPasswordSuccess: 'Tạo mật khẩu thành công',
    cash: 'Tiền mặt',
    checkMaskedFace: 'Khuôn mặt không hợp lệ, vui lòng không đeo kính và khẩu trang khi xác minh!',
    // endregion

    // region D
    designers: 'Designers',
    deal: 'Giao dịch',
    detailsContract: 'Chi tiết hợp đồng',
    details: 'CHI TIẾT',
    dateSuccess: 'Ngày hiệu lực',
    discover: 'Discover',
    description: 'Description',
    dob: 'Ngày sinh',
    date: 'Ngày',
    dateInnitiated: 'Ngày khởi tạo',
    done: 'Hoàn thành',
    defaultAccount: 'Đặt làm tài khoản mặc định',
    day: 'Day',
    doYouNeedHelp:
        'Bạn cần trợ giúp? Vui lòng liên hệ với T99 theo các phương thức sau:',
    download: 'Download',
    detail: 'Chi tiết',
    district: 'Quận/Huyện',
    dateOfBirth: 'Ngày sinh',
    default: 'Mặc định',
    dateRange: 'Ngày cấp',
    doNotBeneficiaryAccount: 'Bạn chưa có tài khoản thụ hưởng',
    digitalFinance: 'Tài chính số',
    digitalPayment: 'Thanh toán số',
    digitalInsurance: 'Bảo hiểm số',
    disbursementForm: 'Hình thức giải ngân',
    disbursementAmount: 'Số tiền giải ngân',
    disbursementDate: 'Ngày giải ngân',
    delete: 'Xoá',
    documentCode: 'Mã giấy tờ',
    documentType: 'Loại giấy tờ',
    detailedAddress: 'Địa chỉ chi tiết ( số nhà, tên đường )',
    debtReceiptCode: 'Mã khế ước nhận nợ',
    doYouWantToContinueApplyLoan: 'Bạn có muốn tiếp tục đăng ký vay.',
    debtPaymentDue: 'Trả nợ đến hạn',
    dateDue: 'Ngày đến hạn',
    dayTransaction: 'Ngày giao dịch',
    disbursementLimit: 'Hạn mức giải ngân',
    disbursementPurpose: 'Mục đích giải ngân',
    disbursementHistory: 'Lịch sử giải ngân',
    disbursementNow: 'Giải ngân ngay',
    disbursement: 'Giải ngân',
    detailsImage: 'Ảnh chi tiết',
    deleteAccountConfirm: 'Bạn có muốn xoá tài khoản này?',
    documentCodeWrong: 'Sai định dạng giấy tờ',
    // endregion

    // region E
    email: 'Email',
    email2: 'info@t99.vn',
    expire: 'Expire',
    expires: 'Expires',
    edit: 'Edit',
    enterThePhoneNumber: 'Nhập số điện thoại để tiếp tục lấy lại mật khẩu.',
    enterReferralCode: 'Nhập Mã giới thiệu',
    enterEmail: 'Nhập email',
    enterPhoneNumber: 'Nhập số điện thoại',
    enterFullname: 'Nhập họ và tên',
    enterFullNameByDocument: 'Nhập họ và tên theo giấy khai sinh',
    electronicIdentityVerification: 'Xác thực định danh điện tử',
    enterFullname2: 'Họ và tên',
    enterCompanyName: 'Nhập tên doanh nghiệp',
    enterTaxNumber: 'Nhập mã số thuế doanh nghiệp',
    enterPosition: 'Nhập chức vụ',
    enterProvince: 'Nhập tỉnh/thành phố',
    enterDistrict: 'Nhập quận/huyện',
    enterWard: 'Nhập phường/xã',
    enterDocumentCode: 'Nhập mã giấy tờ',
    enterDocumentType: 'Nhập loại giấy tờ',
    enterAddress: 'Nhập địa chỉ',
    enterRepresentative: 'Nhập người đại diện',
    enterPhoneContact: 'Nhập số điện thoại liên hệ',
    enterEarnings: 'Nhập thông tin thu nhập',
    enterIdentityDocuments: 'Chọn tài liệu để tải lên',
    earnings: 'Thu nhập',
    expirationDate: 'Ngày hết hạn',
    enterAssetName: 'Nhập tên tài sản',
    error: 'Lỗi',
    errorMessageCommon: 'Đã có lỗi xảy ra',
    enterInterestCalculationInformation: 'Nhập thông tin tính lãi',
    enterMoneyPlaceholder: 'Nhập số tiền',
    estimatedInterestRate: 'Dự tính lãi',
    estimatedContract: 'Lãi suất HĐ dự tính',
    estimatedContractAmount: 'Phí quản lý tài sản HĐ dự tính',
    enterDetailedAddress: 'Nhập địa chỉ chi tiết',
    enterPromoCode: 'Nhập mã khuyến mãi',
    estimatedLoan: 'Khoản vay dự tính',
    ekycSuccessTitle: 'Chúc mừng bạn đã hoàn thành xác thực thông tin',
    extendMonths: 'Số tháng gia hạn',
    enterPassword: 'Nhập mật khẩu',
    earlyRepayment: 'Trả nợ trước hạn',
    // endregion

    // region F
    for: ' for ',
    features: 'Features',
    female: 'Nữ',
    from: 'From',
    forgotPassword: 'Quên mật khẩu?',
    fitness: 'Fitness',
    food: 'Food',
    family: 'Family',
    forYou: 'For you',
    filter: 'Bộ lọc',
    filterAction: 'Lọc',
    faqs: 'FAQs',
    fullname: 'Họ và tên',
    fashionLuxury: 'Thời trang Luxury',
    featuredProducts: 'Sản phẩm nổi bật',
    familyRegisterInformation: 'Thông tin hộ khẩu',
    fixedInterestPlaceholder: 'Lãi cố định',
    forgotPasswordNoQuestionMark: 'Quên mật khẩu',
    fixedAssets: 'Tài sản cố định',
    fee: 'Phí',
    file: 'Hồ sơ',
    fromDate: 'Từ ngày',
    forAdviceAndSupport: 'để được tư vấn và hỗ trợ',
    forConsultingSupport: 'để được hỗ trợ tư vấn',
    featureImproving: 'Tính năng sắp ra mắt!',
    // endregion

    // region G
    grandTotal: 'Grand total',
    goBack: 'Go back',
    getHelp: 'Get help',
    golferAccountVerification: 'Xác thực tài khoản Golfer',
    golferAccountHolder: 'Chủ tài khoản Golfer',
    golf: 'Golf',
    gender: 'Giới tính',
    genderIsRequire: 'Bạn chưa chọn giới tính',
    grantedBy: 'Nơi cấp',
    golferCreditPackage:
        'Gói tín dụng Golfer được thiết kế độc quyền giữa T99 và VGS Holding dành cho các Golfer Việt Nam',
    golferCreditPackage2: 'Gói tín dụng Golfer',
    golfAccountHolde: 'Chủ tài khoản Golf',
    golferCredits: 'Tín dụng Golfer',
    goBackHome: 'Về màn hình chính',
    golferCreditPackageTitle: 'Gói tín dụng Golfer',
    // endregion

    // region H
    history: 'History',
    home: 'Trang chủ',
    haveReadAndAgreeWith: 'Tôi đã đọc và đồng ý với',
    hotline: '1900 077 799',
    hotline2: 'Hotline:',
    hotline3: '1900 565656',

    // endregion

    // region I
    isPhoneNumberValid: 'Số điện thoại không đúng định dạng!',
    isEmailValid: 'Email không đúng định dạng!',
    isPasswordValid: 'Mật khẩu không đúng định dạng!',
    identityDocuments: 'Chứng từ chứng minh thu nhập',
    informationAccount: 'Thông tin tài khoản',
    interestCalculator: 'Tính lãi',
    insuranceFees: 'Phí bảo hiểm',
    identityCard: 'Chứng minh nhân dân',
    investmentCooperation: 'Hợp tác đầu tư',
    invest: 'Bất động sản',
    incomeVerification: 'Xác thực thu nhập',
    identityVerification: 'Xác thực định danh',
    innitiatedDate: 'Ngày khởi tạo',

    interestType: 'Loại lãi suất',
    interestPaymentCycle: 'Chu kỳ trả lãi',
    investmentContractManagement: 'Quản lý hợp đồng đầu tư',
    insurance: 'Bảo hiểm',
    informationQuery: 'Truy vấn thông tin',
    informationDetails: 'Thông tin chi tiết',
    interestRate: 'Lãi suất',
    idCard: 'Số giấy tờ',
    issueDate: 'Ngày cấp',
    investmentContract: 'Hợp đồng đầu tư',
    informationLoanAmount: 'THÔNG TIN KHOẢN VAY',
    incomeSource: 'Nguồn thu nhập',
    interestPayment: 'Thanh toán lãi',
    importContent: 'Nhập nội dung...',
    profit: 'Lãi',

    // endregion

    // region J
    job: 'Nghề nghiệp',

    // endregion

    // region K

    // endregion

    // region L
    loginWithBiometric: 'Đăng nhập với Touch/Face ID',
    loginWithBiometricNotSp: 'Bạn chưa cài đặt đăng nhập với FaceID/TouchID',

    login: 'Đăng nhập',
    loginSuccess: 'Đăng nhập thành công',
    loginFalse: 'Sai tên đăng nhập hoặc mật khẩu',
    lenders: 'Bên cho vay',
    loanContract: 'Hợp đồng vay',
    login2: 'Log in',
    location: 'Location',
    lostInternetConnection: 'Internet connection is unstable.',
    logoutSpace: 'Log out',
    logout: 'Đăng xuất',
    languages: 'Languages',
    loading: 'Loading...',
    learnMore: 'Learn More',
    learnMoreLowerCase: 'Learn more',
    loanAmount: 'Khoản vay',
    learnTheApp: 'Tìm hiểu ứng dụng',
    lifeUtilities: 'Tiện ích đời sống',
    loanInformation: 'Thông tin vay',
    loanInformationExtension: 'THÔNG TIN GIA HẠN KHOẢN VAY',
    loan: 'Số tiền vay',
    loanAmountMustBeAtLeastFrom: 'Số tiền vay phải tối thiểu từ',
    liveness: 'Liveness',
    listOfContracts: 'Danh sách hợp đồng',
    listWallet: 'Danh sách các ví điện tử',
    listAccountT99: 'Danh sách tài khoản T99',
    loanExtension: 'Gia hạn khoản vay',
    loanRequetsExtension: 'YÊU CẦU GIA HẠN KHOẢN VAY',
    loanTime: 'Thời gian gia hạn:',
    loanContractSuccessful: 'Hợp đồng cho vay đã được khởi tạo thành công',
    limit: 'Hạn mức',
    leftFaceImage: 'Ảnh mặt trái',
    limitToExport: 'Hạn mức để xuất',
    listTransactionOffice: 'Xem danh sách các phòng giao dịch',
    // endregion

    // region M
    matchTheOldPassword: 'Trùng với mật khẩu cũ',
    mind: 'Lưu ý',
    mediaChannel: 'Kênh truyền thông',
    money: 'Số tiền',
    monthPlaceholder: 'Tháng',
    male: 'Nam',
    momo: 'Ví Momo',
    viettelPay: 'Ví Viettel Pay',
    vnpt: 'Ví VNPT Pay',
    monthlyRevenue: 'Thu nhập hàng tháng',
    moneyPaid: 'Số tiền phải thanh toán',
    monthlyPaymentAmount: 'Số tiền thanh toán hằng kỳ',
    methodPay: 'Phương thức thanh toán',
    month: 'Tháng',
    minLendingMoney:
        'Số tiền vay tối thiểu phải từ {{minLendingMoney, string}}',
    maxLendingMoney:
        'Số tiền vay tối đa không được vượt quá {{maxLendingMoney, string }}',
    minLendingMoneyMustBeAtLeastFrom:
        'Số tiền vay phải tối thiểu từ {{minLendingMoney}} và không được vượt quá {{maxLendingMoney}}',

    // endregion

    // region N
    noData: 'Không có dữ liệu',
    notVerify: 'Chưa xác thực',
    nearestPGD: 'PGD Gần nhất',
    name: 'Name',
    news: 'Tin tức',
    next: 'Tiếp tục',
    newPassword: 'Mật khẩu mới',
    noThanks: 'No. Thanks',
    continueButton: 'CONTINUE',
    notNow: 'Not Now',
    now: 'Now',
    no: 'No',
    note: 'Ghi chú:',
    noteElectronicIdentityVerification:
        'Quý khách vui lòng xác thực định danh để sử dụng bản Pro đầy đủ tính năng dịch vụ cảu T99 Group.',
    noteGolferAccountVerification:
        'Quý khách vui lòng cung cấp thông tin VGA để được mở các tính năng dành riêng cho Golfer.',
    noteAssetAndIncomeVerification:
        'Quý khách vui lòng cung cấp thông tin bổ sung để được sử dụng dịch vụ với lãi và chi phí ưu đãi.',
    notice: 'Lưu ý: ',
    noAccount: 'Chưa có tài khoản?',
    notVerificationAccount: 'Bạn chưa thực hiện xác minh \n tài khoản',
    notification: 'Thông báo',
    nearestTransactionOffice: 'Phòng giao dịch gần nhất',
    newTerm: 'Kỳ hạn mới',
    newInterestRate: 'Lãi suất mới',
    newQLTSFee: 'Phí QLTS mới',
    newTDTSFee: 'Phí TĐTS mới',
    newPremium: 'Phí Bảo hiểm mới',
    newPrincipalPaymentDate: 'Ngày trả gốc mới',
    newInterestPaymentDate: 'Ngày trả lãi mới',
    notActivatedYet: 'Chưa được kích hoạt',
    numberPlateImage: 'Ảnh biển số',
    nationality: 'Quốc tịch',
    // endregion

    // region O
    ok: 'OK',
    openWeb: 'Open web',
    open: 'Open',
    otpIncorrect: 'OTP không đúng',
    oldPassword: 'Mật khẩu cũ',
    orGoToTheNearestTransactionOfficeOfT99:
        'hoặc đến phòng giao dịch gần nhất của T99',
    orLoginWith: 'Hoặc đăng nhập bằng',
    offerPackage: 'Gói ưu đãi',
    otherFees: 'Phí khác',
    onlinePayment: 'Thanh toán trực tuyến',
    origin: 'Gốc',
    // endregion

    // region P
    password: 'Mật khẩu',
    payNow: 'Thanh toán ngay',
    principal: 'Tiền gốc',
    phoneNumber: 'Số điện thoại',
    phoneNumberPlaceholder: 'Số điện thoại đã đăng ký',
    pleaseTryAgain: 'Please try again.',
    pricing: 'Pricing',
    passwordsMustContain: 'New passwords must contain',
    phoneNumberInValid: 'Số điện thoại không đúng định dạng',
    pleaseProvideInformation:
        'Vui lòng cung cấp thông tin chi tiết cho tài khoản mới của bạn.',
    pleaseLoginToUse: 'Vui lòng đăng nhập để sử dụng.',
    passwordWillSentToTheRegisteredPhoneNumber:
        'Mật khẩu sẽ được gửi về số điện thoại đã đăng ký',
    pleaseEnterNewPassword: 'Vui lòng nhập mật khẩu mới.',
    pleaseEnterInfoPassword: 'Xin vui lòng nhập thông tin mật khẩu. ',
    passwordConditions:
        'Mật khẩu có 8 ký tự, bao gồm: chữ thường, chữ số, chữ in hoa.',
    passwordsMustMatch: 'Mật khẩu phải trùng khớp.',
    propertyInformation: 'Thông tin tài sản',
    position: 'Chức vụ',
    province: 'Tỉnh/Thành phố',
    phoneContact: 'Số điện thoại liên hệ',
    propertyName: 'Tên tài sản',
    policyAndPrivacy: 'Chính sách và bảo mật',
    profileVerified: 'Đã xác thực hồ sơ',
    profileNotVerified: 'Chưa xác thực hồ sơ',
    permanentAddress: 'Địa chỉ thường trú',
    pleaseVerificationInformation:
        'Vui lòng nhập thông tin cá nhân dưới đây để chúng tôi xác thực thông tin của bạn.',
    personal: 'Cá nhân',
    payment: 'Thanh toán',
    profileCode: 'Mã hồ sơ',
    pawn: 'Cầm cố vi mô',
    pleasePerformVerificationByFollow:
        'Vui lòng thực hiện xác minh theo các bước sau:',
    pledgeProperty: 'Cầm cố tài sản',
    pledge: 'Cầm cố',
    period: 'Kỳ hạn',
    principalRepaymentCycle: 'Chu kỳ trả gốc',
    privacyAndPolicy: 'Chính sách bảo mật',
    pleaseEnter0000:
        'Vui lòng nhập 000000 nếu quý khách không có mã giới thiệu',
    pleaseIdentityInformation:
        'Quý khách vui lòng xác thực định danh để sử dụng bản Pro đầy đủ tính năng dịch vụ của T99 Group.',
    pleaseAddFamilyRegister: 'Vui lòng bổ sung hình ảnh sổ hộ khẩu gia đình',
    propertyType: 'Loại tài sản',
    picture: 'Hình ảnh',
    paymentMethod: 'Cách thức thanh toán',
    promoCode: 'Mã khuyến mãi',
    periodicalPaymentAmount: 'Số tiền thanh toán hằng kỳ',
    passport: 'Hộ chiếu',
    payMyContract: 'Thanh toán hợp đồng của tôi',
    paySomeoneElseContract: 'Thanh toán hợp đồng của người khác',
    pleaseEnter: 'Vui lòng nhập',
    providedByThePolicyholder: ' được cung cấp bởi chủ hợp đồng',
    pay: 'Thanh toán',
    partialRepaymentOfPrincipal: 'Trả nợ gốc một phần',
    paymentOfInterestAndFees: 'Thanh toán lãi phí',
    payCashStore: 'Thanh toán tiền mặt tại cửa hàng',
    payAtStore: 'Thanh toán tại cửa hàng',
    payTransfer: 'Thanh toán chuyển khoản ngân hàng',
    principalDebt: 'Dư nợ gốc',
    penaltyFeeSettlement: 'Phí phạt tất toán trước hạn',
    pleaseCopyPaymentContent: 'Vui lòng sao chép nội dung thanh toán:',
    pledgedProperty: 'Tài sản cầm cố',
    payingFee: 'Thanh toán phí',
    paymentTerm: 'Hạn thanh toán',
    productsAndAll:
        'sản phẩm và tất cả các tính năng của T99, xin vui lòng đăng nhập ứng dụng',

    pending: 'Chờ xử lý',
    personalInformation: 'Thông tin cá nhân',
    product: 'Sản phẩm',
    passwordChanged: 'Đổi mật khẩu thành công',
    passwordChangedDescription: 'Bạn đã đổi mật khẩu mới thành công.',
    phoneNumberDoesNotExist: 'Số điện thoại không tồn tại',
    pleaseUploadClearCorrectPhotos: 'Vui lòng tải ảnh rõ nét, đúng yêu cầu',
    payAPart: 'Thanh toán 1 phần',
    payBankTransfer: 'Thanh toán\nchuyển khoản ngân hàng',
    payTheStore: 'Thanh toán tại cửa hàng',
    // endregion

    // region Q
    quickSignIn: 'Quick sign in now',
    overdueFee: 'Phí quá hạn',
    // endregion

    // region R
    remainingAmount: 'Số tiền còn lại cần thanh toán',
    required: 'Required',
    registerNow: 'Đăng ký ngay',
    register: 'Đăng ký',
    requestChangeTheRepayment: 'Yêu cầu thay đổi lịch trả nợ',
    infoChangeTheRepayment: 'THÔNG TIN THAY ĐỔI LỊCH TRẢ NỢ',
    requestChangeTheRepayment2: 'YÊU CẦU THAY ĐỔI LỊCH TRẢ NỢ',
    recommended: 'Recommended',
    requestLoanFaild: 'Gửi yêu cầu không thành công',

    remainingInvestmentRate: 'Tỷ lệ đầu tư còn lại',
    referralCode: 'Mã giới thiệu',
    representative: 'Người đại diện',
    requestDeleteAccount: 'Yêu cầu xóa tài khoản',
    risemountResort: 'Risemount Resort',
    registerService: 'Đăng ký dịch vụ',
    realEstateMortgage: 'Cầm cố Bất động sản',
    registrationLimit: 'Hạn mức đăng ký',
    resultsCompare: 'Kết quả so sánh',
    resultValidation: 'Kết quả xác minh',
    recentLocation: 'Địa chỉ thường trú',
    remainingBalance: 'Dư nợ còn lại',
    registrationPapers: 'Giấy tờ đăng ký',
    registrationPapersPropertyOwnership: 'Giấy tờ đăng ký/ sở hữu tài sản',
    requestFeeWaiver: 'Yêu cầu miễn giảm lãi phí',
    realEstateTransfer: 'Chuyển nhượng BDS',
    realEstateTransfer2: 'T99_Bất động sản',
    requestChangeRepayment: 'Yêu cầu thay đổi lịch trả nợ',
    requestDate: 'Ngày yêu cầu',
    referenceInformation: 'Thông tin người tham chiếu',
    referencePerson: 'Người tham chiếu',
    relationship: 'Quan hệ',
    request: 'Gửi yêu cầu',
    requestSuccess: 'Gửi yêu cầu thành công',
    reenterPassword: 'Nhập lại mật khẩu',
    resign: 'Ký lại',
    rightFaceImage: 'Ảnh mặt phải',
    registrationAmount: 'Số tiền đăng ký',
    riesountResort: 'Riesount Resort',
    reVerify: 'Xác thực lại',
    reject: 'Từ chối',
    // endregion

    // region S
    loginSpace: 'Sign in',
    salesStaffCode: 'Mã nhân viên kinh doanh',
    signin: 'Đăng nhập',
    shop: 'Shop',
    signup: 'Đăng ký',
    selectRatio: 'Chọn tỉ lệ',
    submit: 'Xác nhận',
    success: 'Thành công',
    signupSubText: 'Already have an account?',
    signupBottomSubText:
        'By registering, you have read and agree to our\nterms and conditions and our Privacy Policy',
    signupHere: 'Sign up now',
    signinHere: 'Sign in here',
    signinNow: 'Sign in now',
    sureGotIt: 'Sure. Got it.',
    settings: 'Settings',
    savedOffer: 'Saved offer',
    saveChanges: 'Save Changes',
    scanCardDetail: 'Scan Card Details',
    save: 'Save',
    saving: 'Tiết kiệm',
    searchResults: 'Search Results',
    seeMore: 'Xem thêm',
    shareArticle: 'Share this article',
    select: 'Lựa chọn',
    seeFullDetails: 'See full details',
    startBenefit: 'Start your Benefit',
    support: 'Hỗ trợ',
    skip: 'Bỏ qua',
    setting: 'Cài đặt',
    signNow: 'Ký Ngay',
    sendBackOtp: 'Gửi lại OTP',
    sendBack: 'Gửi lại',
    stringNote:
        'Xin vui lòng nhập chính xác thông tin của bạn để ứng dụng có thể hiển thị chính xác thông tin khoản vay.',
    stringNoteSignup:
        'Vui lòng nhập 000000 nếu quý khách không có mã giới thiệu',
    signupSuccess: 'Đăng ký thành công',
    successfullyRegisteredAnAccount:
        'Chúc mừng bạn đã đăng ký tài khoản thành công.',
    smartOpt: 'SmartOTP',
    smartOpt2: 'Đăng ký Smart OTP',
    selectImage: 'Chọn ảnh',
    selectCareer: 'Lựa chọn ngành nghề',
    selectAuthenticationType: 'Chọn loại xác thực',
    supportCenter: 'Trung tâm trợ giúp',
    settingBiometric: 'Cài đặt Biometric',
    seeTheList: 'Xem danh sách phòng giao dịch',
    simNumber: 'Sim số',
    search: 'Tìm kiếm...',
    status: 'Trạng thái',
    statusContract: 'Trạng thái hợp đồng',
    signContract: 'Ký hợp đồng vay',
    setPassword: 'Đặt mật khẩu ',
    selectDocumentEkycSubTitle:
        'Giấy tờ tùy thân để tiếp tục xác minh tài khoản',
    selectDate: 'Chọn ngày',
    selectTypeOfPaymentContract: 'Chọn loại hợp đồng thanh toán',
    someContracts: 'Số hợp đồng',
    selectMethodPay: 'Chọn phương thức thanh toán',
    signingStyle: 'Hình thức ký',
    successfulLoanRegistration: 'Đăng ký vay thành công',
    successfullyDisbursedRegistration: 'Đăng ký giải ngân thành công',
    signUpToIncreaseYourLimit: 'Đăng ký nâng hạn mức',
    smartSupport: 'Giao dịch thuận tiện - Thủ tục nhanh chóng',
    smartSupport2:
        'Cùng những chức năng đăng ký dịch vụ nhanh chóng - hỗ trợ thông minh cho người dùng',
    safetyHighSecurity: 'Tính an toàn - Bảo mật cao',
    simpleAndEasyOperation: 'Thao tác đơn giản, dễ dàng',
    settlement: 'Tất toán',
    settled: 'Đã tất toán',
    sumSettlement: 'Tổng số tiền cần tất toán',
    stk: 'STK',
    SignTheConfirmation: 'Ký xác nhận',
    signUpForALimit: 'Đăng ký cấp hạn mức',
    sortFeatures: 'Sắp xếp tính năng',
    selectDay: 'Chọn ngày',
    sendOTPSuccess: 'Gửi mã xác thực thành công',
    sendOTPFalse: 'Gửi mã xác thực thất bại',
    t99StoreNearby: 'Cửa hàng T99 gần bạn',
    // endregion
    online: 'Online',
    openAccount: 'Mở tài khoản',
    // region P
    paymentPlan: 'Kế hoạch trả nợ',
    paymentHistory: 'Lịch sử thanh toán',
    pleaseSignHere: 'Mời ký vào đây',
    pleaseContactCallCenter: 'Vui lòng liên hệ tổng đài',
    processed: 'Đã xử lý',
    propertyPictures: 'Hình ảnh tài sản',
    noProcess: 'Chưa xử lý',
    providingInsurance:
        'Cung cấp các đơn vị bảo hiểm phù hợp với nhu cầu cuộc sống của bạn và gia đình',
    pawnProducts: 'Sản phẩm cầm cố',
    paymentOverdue: 'Bạn đã quá hạn thanh toán',
    // region Q
    quickProcedure: 'Giao dịch thuận tiện - Thủ tục nhanh chóng',

    // region T
    transfer: 'Chuyển khoản',
    t99RealEstate: 'T99_Bất động sản',
    t99Pledge: 'T99_Cầm cố',
    t99Golf: 'T99_Golf',
    termsPolicyAndPrivacy: 'Điều khoản chính sách và bảo mật',
    thisFieldRequired: 'Đây là trường bắt buộc!',
    takePhoto: 'Chụp ảnh',
    takeFromLib: 'Chọn ảnh từ thư viện',
    taxNumber: 'Mã số thuế',
    transactionHistory: 'Lịch sử giao dịch',
    theApplicationHelps:
        'Ứng dụng giúp tiếp cận vốn vay có thế chấp tài sản nhanh nhất với các thủ tục đơn giản.',
    transaction: 'Giao dịch',
    transactionType: 'Loại giao dịch',
    touchId: 'Touch ID',
    t99Standard: 'T99 - Standard',
    t99Pro: 'T99 - Pro',
    t99Golfer: 'T99 - Golfer',
    transactionOffice: 'Phòng giao dịch',
    termLimit: 'Kỳ hạn',
    t99: 'T99',
    theNearestTransactionOffice: 'Phòng giao dịch gần nhất',
    t99StoreNearYou: 'Cửa hàng T99 gần bạn',
    temporaryResidenceInformation: 'Thông tin tạm trú',
    selectPropertyType: 'Lựa chọn loại tài sản',
    selectAssetGroup: 'Lựa chọn nhóm tài sản',
    totalAmountToBePaid: 'Tổng số tiền cần thanh toán',
    totalInterestPayable: 'Tổng lãi phí phải trả',
    totalAmountPaid: 'Tổng số tiền đã thanh toán',
    thankYouForTrustingToUseOurService:
        'Cảm ơn bạn đã tin tưởng sử dụng dịch vụ của chúng tôi.',
    totalAmountNeedToPay: 'Tổng số tiền cần thanh toán',
    totalAmountpaid: 'Tổng số tiền đã thanh toán',
    timeOut: 'Thời hạn',
    t99TradingHours:
        'Khung giờ giao dịch của T99 từ 09:00 đến 16:00 các ngày trong tuần',
    target: 'Mục đích',
    toUse: 'Để sử dụng',
    // endregion O
    outstandingFeatures: 'Đặc điểm nổi bật',
    toDate: 'Đến ngày',
    outOfDate: 'Quá hạn',
    // endregion

    // region U
    update: 'Cập nhật',
    utilities: 'Tiện ích',
    unit: 'Đơn vị',
    undue: 'Chưa đến hạn',
    InPeriod: 'Nợ trong hạn', // Nợ trong hạn
    OverPeriod: 'Nợ quá hạn', // Nợ quá hạn
    Liquidation: 'Đã thanh lý', // đã thanh lý
    WaitForLiquidation: 'Chờ thanh lý', // chờ thanh lý
    HasEnded: 'Đã tất toán', // Đã tất toán
    uploadAvatarFailed: 'Thay đổi ảnh đại diện không thành công',
    uploadAvatarSuccess: 'Thay đổi ảnh đại diện thành công',
    // endregion

    // region V
    verificationCode: 'Mã xác thực',
    verificationCodeFalse: 'Xác thực thất bại',
    valueProject: 'Giá trị dự án',
    verifyYourAccount: 'Xác thực tài khoản',
    verifyCompanyOwnershipInformation: 'Xác thực thông tin công ty sở hữu',
    vgaCode: 'Mã VGA',
    verifyIdentityDocument: 'Xác thực giấy tờ tùy thân',
    verifyDocument: 'Xác thực giấy tờ',
    verifyFaceId: 'Xác thực khuôn mặt',
    verifyNow: 'Xác thực ngay',
    validDate: 'Ngày hết hạn',
    validDateIsRequire: 'Bạn chưa chọn ngày hết hạn',
    validPlace: 'Nơi cấp',
    vnd: 'VND',
    variousAndRichUtilities: 'Tiện ích đa dạng và phong phú',
    vehicleRegistrationCertificate: 'Chứng nhận đăng ký xe',
    verified: 'Đã xác thực',
    // endregion R
    requestDisbursement: 'Yêu cầu giải ngân',
    requestDisbursement2: 'YÊU CẦU GIẢI NGÂN',
    requestLimitIncrease: 'Yêu cầu nâng hạn mức',
    referralCode6: 'Mã giới thiệu phải nhỏ hơn 6 kí tự!',
    referrerCodeWrongFormat: 'Sai định dạng mã giới thiệu',
    // region W
    weProvide:
        'Chúng tôi cung cấp Giải pháp sim số và Data 4G hàng đầu Việt Nam',
    weApplyPayment: 'Chúng tôi Ứng dụng công nghệ thanh toán mọi lúc , mọi nơi',
    weProvideBetterFinancial:
        'Chúng tôi cung cấp nhưng dịch vụ tài chính tốt hơn với sự trợ giúp của công nghệ',
    website: 'Website:',
    website2: 'www.t99.vn',
    whenYouGetToTheTradingRoom:
        'Khi đến phòng giao dịch, vui lòng mang đầy đủ các giấy tờ cần thiết',
    ward: 'Phường/Xã',
    waitingSignContract: 'Chờ ký hợp đồng',
    waitingForApproval: 'Chờ duyệt',
    // endregion

    // region I
    interest: 'Tiền lãi',
    infoFeeWaiver: 'THÔNG TIN MIỄN GIẢM LÃI PHÍ',
    infoFeeWaiver2: 'YÊU CẦU MIỄN GIẢM LÃI PHÍ',
    importAmount: 'Nhập số tiền',
    Indebtedness: 'Nợ trong hạn',
    Overdue: 'Nợ quá hạn',
    WaitingForLiquidation: 'Chờ thanh lý',
    Completed: 'Đã tất toán',
    Liquidated: 'Đã thanh lý',

    // endregion

    // region X
    // endregion F

    // region Y
    youHaveAnAccount: 'Đã có tài khoản?',
    youCreatedNewPassword: 'Bạn đã tạo mật khẩu mới thành công.',
    youDoNotHavePropertyInformation: 'Bạn chưa có thông tin tài sản',
    youDoNotHaveIncomeInformation: 'Bạn chưa có thông tin thu nhập',
    youHaveSomeDays: 'Bạn còn {{val, number}} ngày để hoàn thành thanh toán.',
    yourLoanApplicationIsBeingReceived:
        'Hồ sơ vay vốn của Quý khách đang được nghiệp vụ T99 Group tiếp nhận và xử lý. Mọi thông tin vui lòng liên hệ tổng đài',
    yourDisbursementRecordIsBeingReceived:
        'Hồ sơ giải ngân của Quý khách đang được nghiệp vụ T99 Group tiếp nhận và xử lý',
    yourAvailabilityLimit: 'Hạn mức khả dụng của bạn',
    youAreNotEligibleForAGolferCreditLine:
        'Quý khách chưa đủ điều kiện cấp hạn mức tín dụng Golfer',
    yourRequestProcessedByT99:
        'Yêu cầu của Quý khách đang được nghiệp vụ T99 Group tiếp nhận và xử lý.',
    // endregion

    // region Z

    // endregion
    errorsTouchId: {
        LAErrorTouchIDNotEnrolled:
            'Không thể bắt đầu xác thực vì không có ngón tay/khuôn mặt nào được đăng ký.',
        LAErrorTouchIDNotAvailable:
            'Không thể bắt đầu xác thực vì Touch/Face ID không khả dụng trên thiết bị',
        RCTTouchIDNotSupported: 'Thiết bị không hỗ trợ Touch/Face ID',
    },
    errorsEkyc: {
        'IDG-00000000': 'Thành công',
        'IDG-00000001': 'Dữ liệu rỗng',
        'IDG-00000002': 'User không phải là duy nhất trong IDG',
        'IDG-00000003': 'Sai định dạng email',
        'IDG-00000004': 'Độ dài ký tự không thuộc phạm vi từ 1-255',
        'IDG-00000005': 'Kích thước mật khẩu từ 8-50 ký tự',
        'IDG-00000006':
            'Sai định dạng gồm ký tự viết thường, viết hoa, chữ và số, và ký tự đặc biệt',
        'IDG-00000007': 'Sai là định dạng DD/MM/YYYY',
        'IDG-00000050': 'Không kết nối được tới service AI',
        'IDG-00010002': 'Lỗi dữ liệu ảnh đầu vào không đúng format',
        'IDG-00010003': 'Nội dung ảnh đầu vào không hợp lệ',
        'IDG-00010004': 'Hệ thống đang bận',
        'IDG-00010101': 'Lỗi phân loại giấy tờ',
        'IDG-00010102': 'Lỗi dữ liệu ảnh đầu vào phân loại giấy tờ',
        'IDG-00010201': 'Lỗi nhận dạng ký tự trên ảnh giấy tờ',
        'IDG-00010202': 'Lỗi dữ liệu ảnh đầu vào ocr',
        'IDG-00010301': 'Lỗi nhận dạng ký tự trên ảnh giấy tờ mặt trước',
        'IDG-00010302': 'Lỗi dữ liệu ảnh đầu vào ocr mặt trước',
        'IDG-00010401': 'Lỗi nhận dạng ký tự trên ảnh giấy tờ mặt sau',
        'IDG-00010402': 'Lỗi dữ liệu ảnh đầu vào ocr mặt sau',
        'IDG-00010501': 'Lỗi so sánh mặt',
        'IDG-00010502': 'Lỗi dữ liệu ảnh đầu vào so sánh mặt',
        'IDG-00010445': 'Loại giấy tờ không hợp lệ',
    },
    errors: {
        MSG001: 'Vui lòng nhập tên người dùng.',
        MSG002: 'Tên người dùng chỉ có thể bao gồm các chữ cái và số.',
        MSG003: 'Tên người dùng phải có 6-32 ký tự.',
        MSG004: 'Vui lòng nhập tên công ty.',
        MSG005: 'Vui lòng nhập email.',
        MSG006: 'Email không đúng định dạng.',
        MSG007: 'Vui lòng nhập mật khẩu.',
        MSG008: 'Mật khẩu quá ngắn. Mật khẩu phải chứa ít nhất 8 ký tự.',
        MSG009: 'Vui lòng không nhập kí tự đặc biệt.',
        MSG010: 'Mật khẩu phải chứa ít nhất 1 chữ số.',
        MSG011: 'Mật khẩu phải chứa ít nhất 1 chữ thường.',
        MSG012: 'Mật khẩu phải chứa ít nhất 1 chữ in hoa.',
        MSG000: 'Cập nhật mật khẩu thành công.',
        MSG013: 'Vui lòng nhập Website URL.',
        MSG014: 'Website URL không hợp lệ.',
        MSG015: 'Hồ sơ công ty đã tuyên bố!',
        MSG022: 'Token không hợp lệ hoặc đã hết hạn',
        MSG017: 'Email đã tồn tại.',
        MSG018: 'Email hoặc mật khẩu bạn đã nhập không chính xác.',
        MSG019: 'Mật khẩu không đúng.',
        MSG020: 'Các mật khẩu đã nhập không khớp. Hãy thử lại.',
        MSG021: 'Có lỗi xảy ra. Vui lòng thử lại.',
        MSG023: 'Email đã được xác minh.',
        MSG024: 'Email bạn nhập không đúng.',
        MSG025: 'Số điện thoại không hợp lệ',
        MSG036: 'Website đã tồn tại.',
        MSG027: 'Vui lòng nhập tên.',
        MSG028: 'Tên đã tồn tại.',
        MSG031: 'Tên không hợp lệ',
        MSG026: 'URL đã tồn tại',
        MSG029: 'Thứ tự hiện thị không hợp lệ.',
        MSG030: 'Vui lòng nhập thứ tự hiển thị.',
        MSG032: 'Tổng số đánh giá không hợp lệ.',
        MSG033: 'Vui lòng nhập đánh giá',
        MSG034: 'Điểm đánh giá không hợp lệ.',
        MSG035: 'Vui lòng nhập điểm đánh giá.',
        MSG037: 'Yêu cầu dữ liệu không hợp lệ.',
        MSG038: 'Không thể tìm thấy người dùng !.',
        MSG039: 'Không thể tìm thấy thông tin cá nhân của khách hàng !.',
        MSG040: 'Không thể xác định thông tin người dùng !.',
        MSG041: '{0} không thể để trống !.',
        MSG042: 'Xác minh {0} thành công.',
        MSG043: '{0} không tồn tại !.',
        MSG044: 'Cập nhật thành công !.',
        MSG045: 'Gửi Otp không thành công !.',
        MSG046: 'Gửi Otp thành công !.',
        MSG047: 'Đăng ký thành công !.',
        MSG048: 'Xác minh {0} thất bại !.',
        MSG049: 'Mã Ota đã hết hạn !.',
        MSG050: 'Nhập Otp sai {0} lần. Vui lòng gửi lại Otp !.',
        MSG051: 'Thông tin nhận dạng không chính xác !.',
        MSG052: 'Nhập lại mật khẩu không khớp !.',
        MSG053: 'Cập nhật mật khẩu không thành công, hết thời gian yêu cầu Otp. Vui lòng gửi lại Otp !.',
        MSG054: 'Đặt mật khẩu thất bại !.',
        MSG055: 'Đặt mật khẩu thành công !.',
        MSG056: 'Đổi mật khẩu thất bại !.',
        MSG057: 'Đổi mật khẩu thành công !.',
        MSG058: 'Mật khẩu phải có ít nhất 8 ký tự, ít nhất 1 chữ số, 1 chữ hoa, 1 chữ thường, 1 ký tự đặc biệt !.',
        MSG059: 'Số điện thoại đã tồn tại!',
        MSG060: 'Thông tin người dùng đã eKyc !.',
        MSG061: 'Trùng số tài khoản ngân hàng !.',
        MSG062: 'Số giấy tờ đã tồn tại !.',
    },
};
